### ISSUE TITLE
Can't get table to knit to pdf when using tab_header()

### ISSUE THREAD

**Issue by wspagnola** [rstudio/gt#623] opened 2020-07-17 14:00 UTC
When I use the tab_header() function, the code works fine in the markdown file but I get an error when I try to knit the table to a pdf.

```r
iris_tab <- iris %>% 
              group_by(Species) %>% 
              summarize_all(.funs = mean) %>% 
              gt() 


tab_header(data = iris_tab, title = "Iris_Means")
```

! LaTeX Error: There's no line here to end.

Error: LaTeX failed to compile test_RDD_bw.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test_RDD_bw.log for more info.
Execution halted

**Comment by jonathan-g** [comment] 2020-07-17 21:45
This is a duplicate of #463. This bug is fixed by PR #464. 

Until the PR is merged in this repository, I have made a fork with the PR applied at https://github.com/jonathan-g/gt (from R, `remotes::install_github("jonathan-g/gt")`

**Closed** 2021-06-07 19:00 UTC
Labels: Difficulty: [2] Intermediate, Effort: [2] Medium, Priority: ♨︎ Critical, Type: ☹︎ Bug
