### ISSUE TITLE
Add ability for summary functions to refer to columns other than the output column

### ISSUE THREAD

**Issue by travis-leith** [rstudio/gt#690] opened 2020-11-20 13:00 UTC
In my experience it is uncommon to want to have a summary row in a table that uses a univariate function for all columns (as is the case in gt now - v0.2.2).
More commonly I want to apply, for example, a sum to some columns (such as trade value) and a weighted average to others (such as average trade price. In order to do this I would need a way for those functions to reference columns other than that for which the output is for. Such as the summary for column x should be `sum(x*y)/sum(y)`

**Comment by rich-iannone** [comment] 2020-12-01 20:57
This is a great idea, thanks for posting it here. Totally agree that summarizing is a bit simplistic right now.

**Comment by jamesking420** [comment] 2021-01-12 21:12
Yes, I need this, for example, for calculating a rate.  I have a column with "number of cases", and another column with rate, split by region (where rate is cases/population for a given region).  To calculate an overall rate for my summary, I need (sum cases)/(sum population). Not possible to do it with just the vector of the individual column.

**Comment by nicomunting** [comment] 2021-12-21 10:25
I ran into the same limitation. It would be nice if this capability was added in v0.4.0. 

As a workaround (or dirty hack) I just passed a vector with the weights directly to the `weighted.mean` function. 

``` r
df <- tibble::tribble(
  ~price, ~value,
  5, 4,
  2, 6,
  3, 1
)

df %>% 
  dplyr::mutate(value_pct = value / price) %>% 
  gt() %>% 
  summary_rows(fns = list(total = ~ sum(.)), columns = c(value, price)) %>% 
  summary_rows(
    fns = list(total = ~ weighted.mean(., w = df$price)), 
    columns = value_pct,
    formatter = fmt_percent, decimals = 0
  ) %>% 
  fmt_percent(columns = contains("pct"), decimals = 0)
```

By the way, is this not a duplicate of #383?

**Comment by rich-iannone** [comment] 2022-08-25 01:14
Now solved with https://github.com/rstudio/gt/pull/1018

**Closed by rich-iannone** 2022-08-25 01:14 UTC
Labels: Difficulty: [3] Advanced, Effort: [3] High, Priority: [2] Medium, Type: ★ Enhancement
