### ISSUE TITLE
resolve_cols_i fails on connect

### ISSUE THREAD

**Issue by meztez** [rstudio/gt#1507] opened 2023-12-12 14:51 UTC
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

I'm still trying to figure why rendering on connect fails and knitting locally works.

Example Rmd block

```{r cars}
bob <- "carb"
library(gt)
gt(mtcars) |>
  cols_label(contains(bob)~bob)
```
Error in deploy
```
Error in `resolve_cols_i()`:
! Problem while evaluating `contains(bob)`.
Caused by error:
! object 'bob' not found
Backtrace:
  1. gt::cols_label(gt(mtcars), contains(bob) ~ bob)
 22. tidyselect::contains(bob)
 23. tidyselect:::check_match(match)
 24. rlang::is_character(match)
Execution halted
Unable to render the deployed content: Rendering exited abnormally: exit status 1
```

But you can do an eval parse and it will work.
```
col_labels(eval(parse(text = "contains(%s)~%s" |> sprintf(bob, bob))))
```
I'm thinking is some funky env eval going on.

## Reproducible example

* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

Full stacktrace
```
 1: cols_label(gt(mtcars), contains(bob) ~ bob)
 2: resolve_cols_c(expr = !!cols, data = .data)
 3: resolve_cols_i(expr = {
    {
        expr
    }
}, data = data, 
 4: suppressWarnings(tidyselect::eval_select(expr = quo, data = d
 5: withCallingHandlers(expr, warning = function(w) if (inherits(
 6: tidyselect::eval_select(expr = quo, data = data, strict = str
 7: eval_select_impl(data, names(data), as_quosure(expr, env), in
 8: with_subscript_errors(out <- vars_select_eval(vars, expr, str
 9: try_fetch(expr, vctrs_error_subscript = function(cnd) {
    cn
10: withCallingHandlers(expr, condition = function(cnd) {
    {
   
11: vars_select_eval(vars, expr, strict = strict, data = x, name_
12: walk_data_tree(expr, data_mask, context_mask)
13: eval_context(expr, context_mask, call = error_call)
14: with_chained_errors(eval_tidy(as_quosure(expr, env), context_
15: try_fetch(expr, error = function(cnd) {
    eval_expr <- quo_s
16: tryCatch(withCallingHandlers(expr, condition = function(cnd) 
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatchOne(expr, names, parentenv, handlers[[1]])
19: doTryCatch(return(expr), name, parentenv, handler)
20: withCallingHandlers(expr, condition = function(cnd) {
    {
   
21: eval_tidy(as_quosure(expr, env), context_mask)
22: contains(bob)
23: check_match(match)
24: is_character(match)
```

Sessinfo
```
## R version 4.3.2 (2023-10-31)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 22.04.3 LTS
## 
## Matrix products: default
## BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
## LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0
## 
## locale:
##  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
##  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
##  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
## [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
## 
## time zone: America/Montreal
## tzcode source: system (glibc)
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] gt_0.10.0
## 
## loaded via a namespace (and not attached):
##  [1] vctrs_0.6.5      cli_3.6.2        knitr_1.45       rlang_1.1.2     
##  [5] xfun_0.41        generics_0.1.3   jsonlite_1.8.8   glue_1.6.2      
##  [9] htmltools_0.5.7  sass_0.4.8       fansi_1.0.6      rmarkdown_2.25  
## [13] evaluate_0.23    jquerylib_0.1.4  tibble_3.2.1     fastmap_1.1.1   
## [17] yaml_2.3.8       lifecycle_1.0.4  compiler_4.3.2   dplyr_1.1.4     
## [21] pkgconfig_2.0.3  digest_0.6.33    R6_2.5.1         tidyselect_1.2.0
## [25] utf8_1.2.4       pillar_1.9.0     magrittr_2.0.3   bslib_0.6.1     
## [29] tools_4.3.2      xml2_1.3.6       cachem_1.0.8
```

**Comment by olivroy** [comment] 2024-07-10 03:39
Duplicate of #1546

**Closed by olivroy** 2024-07-10 03:39 UTC
Labels: Type: ☹︎ Bug
