### ISSUE TITLE
row selection reactive variable needed for shiny app

### ISSUE THREAD

**Issue by sanjmeh** [rstudio/gt#1368] opened 2023-07-09 18:55 UTC
## Prework
couldn't find any similar request in the issue list

## Proposal

There is a `DT` package in R that is adopted from JS datatable package. This means a lot of its features are hidden and have to be passed through nested list(), which is very hard to remember. The only reason we still use DT package is the `input$tabname_rows_selected` reactive variable that is not available in `gt` (as yet). 

I suggest `gt` package to also allow row selection to be detected in a shiny app as an `input$..` variable. Then gt would be a compelling replacement of the DT package.

**Comment by rich-iannone** [comment] 2023-07-20 11:56
Could you provide an example? I’m not a heavy user of DT right now, so this would be helpful.

**Comment by iainmwallace** [comment] 2024-07-22 02:35
Hi, 

Is this type of functionality possible in an interactive gt table in Shiny?

Thanks

Iain

**Comment by sanjmeh** [comment] 2024-07-22 03:45
> Is this type of functionality possible in an interactive gt table in Shiny?

Not yet. But request @rich-iannone to consider it. It a powerful interactivity function missing in `gt`.

**Comment by maxheld83** [comment] 2024-08-19 18:33
Can this be closed as a duplicate of https://github.com/rstudio/gt/issues/354?

**Closed** 2024-11-06 17:05 UTC
Labels: Type: ★ Enhancement
