### ISSUE TITLE
Unable to Install gt due to juicyjuice and V8 package dependencies

### ISSUE THREAD

**Issue by lanacodes123** [rstudio/gt#1385] opened 2023-07-24 17:18 UTC
MacOS: Ventura 13.4.1 
R studio: "Ghost Orchid" Release (077589bc, 2021-09-20) for macOS

I am unable to install gt, and the solution proposed in issue #1302 is not working. I have tried installing gt on its own, as well as pre-installing V8 and juicyjuice, and none of these solutions work. I receive the following error.

> install.packages("gt")
also installing the dependencies ‘V8’, ‘juicyjuice’

Warning in install.packages :
  unable to access index for repository http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘V8’
Do you want to attempt to install these from sources? (Yes/no/cancel) yes
installing the source packages ‘V8’, ‘juicyjuice’, ‘gt’

trying URL 'http://cran.rstudio.com/src/contrib/V8_4.3.3.tar.gz'
Content type 'application/x-gzip' length 678153 bytes (662 KB)
==================================================
downloaded 662 KB

trying URL 'http://cran.rstudio.com/src/contrib/juicyjuice_0.1.0.tar.gz'
Content type 'application/x-gzip' length 1121080 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'http://cran.rstudio.com/src/contrib/gt_0.9.0.tar.gz'
Content type 'application/x-gzip' length 1506998 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
** using staged installation
Found C++17 compiler: clang++ -arch arm64
Using autobrew bundle: v8-11.2.214.9-universal.tar.xz
** libs
rm -f V8.so RcppExports.o bindings.o
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpK3Et4n/R.INSTALLecd6b722ab7/V8/.deps/include -DV8_COMPRESS_POINTERS -DV8_ENABLE_SANDBOX -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpK3Et4n/R.INSTALLecd6b722ab7/V8/.deps/include -DV8_COMPRESS_POINTERS -DV8_ENABLE_SANDBOX -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c bindings.cpp -o bindings.o
clang++ -arch arm64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o V8.so RcppExports.o bindings.o -L/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpK3Et4n/R.INSTALLecd6b722ab7/V8/.deps/lib -lv8_monolith -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/00LOCK-V8/00new/V8/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
sh: line 1:  4026 Trace/BPT trap: 5       R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T//RtmpK3Et4n/fileecd4561ef50'
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/V8’
Warning in install.packages :
  installation of package ‘V8’ had non-zero exit status
**ERROR: dependency ‘V8’ is not available for package ‘juicyjuice’**
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/juicyjuice’
Warning in install.packages :
  installation of package ‘juicyjuice’ had non-zero exit status
**ERROR: dependency ‘juicyjuice’ is not available for package ‘gt’**
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/gt’
Warning in install.packages :
  installation of package ‘gt’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpBEfd2U/downloaded_packages’

**Comment by olivroy** [comment] 2024-07-16 01:58
Duplicate of #1284

**Closed** 2024-07-16 01:58 UTC
Labels: Type: ⁇ Question
