### ISSUE TITLE
Cross references don't work in HTML

### ISSUE THREAD

**Issue by malcolmbarrett** [rstudio/gt#719] opened 2021-03-02 23:35 UTC
Using `caption` doesn't quite work for `bookdown::html_document2()`

Reprex: https://rstudio.cloud/project/2259811

Screenshot:

<img width="995" alt="Screen Shot 2021-03-02 at 3 32 21 PM" src="https://user-images.githubusercontent.com/23123711/109729510-d0851880-7b6c-11eb-851f-890f98fd7102.png">

**Comment by rich-iannone** [comment] 2021-03-15 00:27
Sorry about the delay on this. Agree that this is a problem. @cderv do you know if this is an easy fix, given that {gt} already has support for `html_document`?

**Comment by cderv** [comment] 2021-03-15 09:46
Currently **gt** does not have support out-of-the-box for **bookdown** caption. This means the manual way must be used as documented: https://bookdown.org/yihui/bookdown/tables.html (at the end of the page) 

> To be able to cross-reference a Markdown table, it must have a labeled caption of the form Table: (\#label) Caption here, where label must have the prefix tab:, e.g., tab:simple-table.
> If you decide to use other R packages to generate tables, you have to make sure the label for the table environment appears in the beginning of the table caption in the form (\#label) (again, label must have the prefix tab:).

````markdown
---
title: "Untitled"
author: "Malcolm Barrett"
date: "3/2/2021"
output: 
  bookdown::html_document2: default
  bookdown::pdf_document2: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Cross-references for gt tables seem to work on PDF but not HTML.

Check out Table \@ref(tab:gt-table)

```{r gt-table, echo = FALSE}
gt::gt(mtcars[1:5, 1:5], caption = "(#tab:gt-table) Test table 1")
```

Now see see Table \@ref(tab:mtcars).

```{r mtcars, echo=FALSE}
knitr::kable(mtcars[1:5, 1:5], caption = "Test table 2")
```
````

![image](https://user-images.githubusercontent.com/6791940/111133962-682a3400-857b-11eb-9f02-a9a8cfef1991.png)


If you want full support, you need to preprend this in the caption text pass by user. There is a trick you can find in the code of how it works for `knitr::kable()`. You also need to deal with the various output format.

**Comment by cderv** [comment] 2021-03-15 10:08
Oh sorry, I did not look at the code. It seems it is supposed to be supported as you are using `knitr:::kable_caption` and `knitr:::create_label` with a copy of it. 

So this is indeed not working. As in my screenshot above. Numbering is ok but the cpation in the table is not. 🤔

Sorry for my too quick answer

**Comment by cderv** [comment] 2021-03-15 10:19
I believe the issue is only the escaping of the hash. You don't need that as your are outputting HTML directly with I don't think is process by Pandoc. You need to remove this `(\\#` and use only `(#`

**Comment by cderv** [comment] 2021-03-15 10:28
Removing the escape characters indeed works. But the label part is not removed in the caption. 
This is because 
```r
  <caption>(#tab:gt-table)Test table 1</caption>
```
is not matched but without leading whitespace it is.
```r
<caption>(#tab:gt-table)Test table 1</caption>
``` 

This should be fixed in **bookdown** maybe for it to work with future bookdown - but if you removed the indentation if should work with past bookdown too.

**Comment by cderv** [comment] 2021-03-15 14:14
Oups @rich-iannone the keyword in bookdown's PR have closed this 😁 

I let you reopen 😄

**Closed** 2021-03-15 18:34 UTC
Labels: Difficulty: [2] Intermediate, Effort: [2] Medium, Priority: ♨︎ Critical, Type: ★ Enhancement

**Comment by malcolmbarrett** [comment] 2021-03-15 19:26
Beautiful, thanks all!

Output with dev versions of gt and bookdown (as expected):
<img width="989" alt="Screen Shot 2021-03-15 at 12 25 24 PM" src="https://user-images.githubusercontent.com/23123711/111209666-8c8d0d00-8589-11eb-9d61-2b27d21295d4.png">

**Comment by cderv** [comment] 2021-03-15 20:27
Great ! Thanks for the report!
