### ISSUE TITLE
tab_options in quarto ignored

### ISSUE THREAD

**Issue by olivroy** [rstudio/gt#1030] opened 2022-08-30 18:00 UTC
## Description

The tab_options don't work in a Quarto html output.

The bold font doesn't appear for groups.

## Reproducible example

```r
library(dplyr)
library(gt)
mtcars |> 
  group_by(vs) |> 
  summarise(mpg = mean(mpg), .groups = "keep") |> 
  gt::gt() |> 
  gt::tab_options(row_group.font.weight = "bold")
```

## Expected result

![image](https://user-images.githubusercontent.com/52606734/187509159-342b8558-e5de-4faa-8670-e153d18ee6f8.png)

Quarto output (v1.1.163)
![image](https://user-images.githubusercontent.com/52606734/187509352-f7dd54f8-78ab-4f35-9478-5714ef484f49.png)

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.
``` r
library(dplyr)
library(gt)
mtcars |> 
  group_by(vs) |> 
  summarise(mpg = mean(mpg), .groups = "keep") |> 
  gt::gt() |> 
  gt::tab_options(row_group.font.weight = "bold")
```

<sup>Created on 2022-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value
#>  version  R version 4.1.0 (2021-05-18)
#>  os       Windows 10 x64 (build 19042)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  French_Canada.1252
#>  ctype    French_Canada.1252
#>  tz       America/New_York
#>  date     2022-08-30
#>  pandoc   2.14.0.3 @ C:/Program Files/RStudio/bin/pandoc/ (via rmarkdown)
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date (UTC) lib source
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.1)
#>  cli           3.3.0      2022-04-25 [1] CRAN (R 4.1.3)
#>  colorspace    2.0-3      2022-02-21 [1] CRAN (R 4.1.2)
#>  DBI           1.1.3      2022-06-18 [1] CRAN (R 4.1.3)
#>  digest        0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
#>  dplyr       * 1.0.9      2022-04-28 [1] CRAN (R 4.1.0)
#>  ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.2)
#>  evaluate      0.15       2022-02-18 [1] CRAN (R 4.1.2)
#>  fansi         1.0.3      2022-03-24 [1] CRAN (R 4.1.3)
#>  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.1)
#>  fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
#>  generics      0.1.3      2022-07-05 [1] CRAN (R 4.1.0)
#>  ggplot2       3.3.6      2022-05-03 [1] CRAN (R 4.1.3)
#>  glue          1.6.2      2022-02-24 [1] CRAN (R 4.1.2)
#>  gt          * 0.7.0      2022-08-25 [1] CRAN (R 4.1.3)
#>  gtable        0.3.0      2019-03-25 [1] CRAN (R 4.1.1)
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.1.1)
#>  htmltools     0.5.3      2022-07-18 [1] CRAN (R 4.1.3)
#>  knitr         1.40       2022-08-24 [1] CRAN (R 4.1.3)
#>  lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.1.3)
#>  munsell       0.5.0      2018-06-12 [1] CRAN (R 4.1.1)
#>  pillar        1.8.1      2022-08-19 [1] CRAN (R 4.1.3)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.1)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.1)
#>  R.cache       0.15.0     2021-04-30 [1] CRAN (R 4.1.1)
#>  R.methodsS3   1.8.1      2020-08-26 [1] CRAN (R 4.1.1)
#>  R.oo          1.25.0     2022-06-12 [1] CRAN (R 4.1.3)
#>  R.utils       2.12.0     2022-06-28 [1] CRAN (R 4.1.3)
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
#>  reprex        2.0.1      2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang         1.0.4      2022-07-12 [1] CRAN (R 4.1.3)
#>  rmarkdown     2.16       2022-08-24 [1] CRAN (R 4.1.3)
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.1)
#>  sass          0.4.1      2022-03-23 [1] CRAN (R 4.1.3)
#>  scales        1.2.1      2022-08-20 [1] CRAN (R 4.1.3)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
#>  stringi       1.7.8      2022-07-11 [1] CRAN (R 4.1.0)
#>  stringr       1.4.1      2022-08-20 [1] CRAN (R 4.1.3)
#>  styler        1.7.0.9001 2022-06-06 [1] Github (r-lib/styler@cffab1e)
#>  tibble        3.1.8      2022-07-22 [1] CRAN (R 4.1.3)
#>  tidyselect    1.1.2      2022-02-21 [1] CRAN (R 4.1.2)
#>  utf8          1.2.2      2021-07-24 [1] CRAN (R 4.1.1)
#>  vctrs         0.4.1      2022-04-13 [1] CRAN (R 4.1.3)
#>  withr         2.5.0      2022-03-03 [1] CRAN (R 4.1.2)
#>  xfun          0.32       2022-08-10 [1] CRAN (R 4.1.3)
#>  yaml          2.3.5      2022-02-21 [1] CRAN (R 4.1.2)
#> 
#> 
#> ------------------------------------------------------------------------------
```

</details>

**Comment by rich-iannone** [comment] 2022-08-30 19:55
Thanks for reporting this. This is a known issue (https://github.com/quarto-dev/quarto-cli/issues/2222) and will be fixed soon.

**Comment by cscheid** [comment] 2022-08-30 23:17
Hm. I'm having a hard time reproducing this one, though. This is the output I see with the latest version of quarto, and the 0.7.0 version of gt installed:

````
---
title: GT quarto
---

```{r}
library(dplyr)
library(gt)
mtcars |> 
  group_by(vs) |> 
  summarise(mpg = mean(mpg), .groups = "keep") |> 
  gt::gt() |> 
  gt::tab_options(row_group.font.weight = "bold")
```
````

Are you running inside RStudio? If so, which version are you using?

**Comment by cscheid** [comment] 2022-08-30 23:27
Ok, I know what the issue is in this particular case.

Unfortunately, a number of quarto features require a modern web browser (in this particular case, the feature is a CSS fixup that quarto performs on GT's styles so that they play nicely with quarto theming). The next version of RStudio IDE that is built on Electron supports them, but RStudio IDE versions that are based on QtWebEngine will not work.

If you click on "About RStudio" and see this:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/285675/187560758-83b11e09-1662-44e5-ab07-0cbe3ae20a34.png">

then you are running a version where some features won't work. You can either:

- try the experimental Electron version of  Spotted Wakerobin (the codename of RStudio's current release, 2022.07) here: https://dailies.rstudio.com/rstudio/spotted-wakerobin/
- or try the RStudio dailies for Elsbeth Geranium, which are all based on Electron: https://dailies.rstudio.com/

**Closed** 2022-08-30 23:27 UTC
Labels: Type: ☹︎ Bug
