### ISSUE TITLE
cell_borders() does not overwrite top and bottom border of body unless weight is set to px(2) or greater

### ISSUE THREAD

**Issue by joshm-idesign** [rstudio/gt#1895] opened 2024-09-27 23:20 UTC
## Prework

* [ x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [ x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

When I try to edit the borders of cells, cell_borders() fails to overwrite the very top and very bottom border of a table's body unless its weight variable is set to px(2) or greater.

## Reproducible example

```
head(iris) |> 
gt() |> 
tab_style(style = cell_borders(sides = "all", color = "red", weight = px(2)), locations = cells_body())
```
Produces a table where all body borders are red and have a 2 pixel weight.
<img src = "https://github.com/user-attachments/assets/f4a6fefd-fc58-47e1-9348-2075a3d3e7e8" width = "500" />

whereas
```
head(iris) |> 
gt() |> 
tab_style(style = cell_borders(sides = "all", color = "red", weight = px(1)), locations = cells_body())
```
Produces a table where all interior and side borders are red and have a 1 pixel weight, but the very top and very bottom borders of the body remain their default values (2 pixel weight gray borders).

<img src = "https://github.com/user-attachments/assets/595baca1-4a56-439e-bcd1-23c485eb26c2" width = "500" />

## Expected result

To my understanding, both calls should overwrite the top and bottom borders of the body, so that even at smaller border weights the top and bottom borders would be colored red.

## Session info

```
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gtExtras_0.5.0    gt_0.11.0         data.table_1.15.2 dplyr_1.1.4       pins_1.3.0       

loaded via a namespace (and not attached):
 [1] rappdirs_0.3.3    sass_0.4.8        utf8_1.2.4        generics_0.1.3    xml2_1.3.6       
 [6] stringi_1.8.3     digest_0.6.34     magrittr_2.0.3    grid_4.3.3        evaluate_0.23    
[11] timechange_0.3.0  pkgload_1.4.0     fastmap_1.1.1     cellranger_1.1.0  jsonlite_1.8.8   
[16] writexl_1.5.0     rematch2_2.1.2    promises_1.2.1    httr_1.4.7        purrr_1.0.2      
[21] fansi_1.0.6       scales_1.3.0      cli_3.6.2         shiny_1.8.0       crayon_1.5.2     
[26] rlang_1.1.3       munsell_0.5.0     ellipsis_0.3.2    withr_3.0.0       yaml_2.3.8       
[31] tools_4.3.3       colorspace_2.1-0  ggplot2_3.5.0     httpuv_1.6.14     paletteer_1.6.0  
[36] curl_5.2.1        vctrs_0.6.5       R6_2.5.1          mime_0.12         lifecycle_1.0.4  
[41] lubridate_1.9.3   stringr_1.5.1     htmlwidgets_1.6.4 fs_1.6.3          fontawesome_0.5.2
[46] pkgconfig_2.0.3   gtable_0.3.4      pillar_1.9.0      later_1.3.2       glue_1.7.0       
[51] Rcpp_1.0.12       xfun_0.42         tibble_3.2.1      tidyselect_1.2.0  rstudioapi_0.15.0
[56] knitr_1.45        xtable_1.8-4      htmltools_0.5.7   rmarkdown_2.26    compiler_4.3.3   
[61] readxl_1.4.3

```

**Comment by olivroy** [comment] 2024-10-03 00:04
Seems to be a duplicate of https://github.com/rstudio/gt/issues/600.

**Comment by joshm-idesign** [comment] 2024-10-03 15:19
> Seems to be a duplicate of #600.

Thank you for that find! It didn't come up on my searching, but yes will close as a dupe.

**Closed** 2024-10-03 15:20 UTC
Labels: Type: ☹︎ Bug

**Comment by olivroy** [comment] 2024-10-03 15:27
Great! I can't say for sure, but this is probably low on the task list!
