### ISSUE TITLE
rotate text on labels

### ISSUE THREAD

**Issue by gvwilson** [rstudio/gt#169] opened 2019-02-06 22:53 UTC
I would like to be able to rotate the text labels on a table. For example, I have a long label I want to put on the Y axis - I would like to be able to rotate the text 90°. I would also like to be able to rotate the text labels on the X axis 90° to make the table more compact.

**Comment by rich-iannone** [comment] 2019-02-21 14:20
Thanks for the feature request. Seems very sensible to be able to rotate the labels (both column labels and the row group labels). We will explore this a bit and come back with some draft implementations in this issue.

**Comment by rich-iannone** [comment] 2021-04-27 19:20
Duplicate of #108

**Closed by rich-iannone** 2021-04-27 19:20 UTC
Labels: Difficulty: [3] Advanced, Effort: [3] High, Priority: [2] Medium, Type: ★ Enhancement
