### ISSUE TITLE
gtsave() drops cell_text(weight)

### ISSUE THREAD

**Issue by nickvence** [rstudio/gt#789] opened 2021-06-04 20:39 UTC
The following code creates red, bold column-labels.
When I pipe it to gtsave(), the labels are saved as red, but are no longer bold (or any other weight).

```r
tibble(client = c("Axy"),
       x = c(0.1),
       y = c(0.2)) %>% 
gt(rowname_col = "client") %>% 
  tab_style(
    style = cell_text(weight = "bold", color = "red"),
    locations = list(cells_row_groups(), cells_column_labels())
  ) 
```
base 4.0.3
tidyverse 1.3.0
gt 0.3.0
webshot 0.5.2

**Comment by rich-iannone** [comment] 2021-06-12 17:58
This is unfortunately a known issue (see the open issue https://github.com/rstudio/gt/issues/621 for more information and a workaround) and I’m sorry you hit upon it. 

This will eventually get resolved after a CRAN release of `webshot2` (which doesn’t rely on phantomjs, where this bug originates). For now, you’ll have to be wary of the limitation of `gtsave()` and use the workaround as appropriate. 

Closing this issue as it’s a duplicate of https://github.com/rstudio/gt/issues/621.

**Closed by rich-iannone** 2021-06-12 17:58 UTC
Labels: Type: ⁇ Question
