### ISSUE TITLE
grand_summary_rows() doesn't work with opt_interactive()

### ISSUE THREAD

**Issue by 22ermiller** [rstudio/gt#1861] opened 2024-08-23 17:32 UTC
I want to add a summary row to the bottom of my gt table and keep the table interactive but whenever I add opt_interactive() to my table, the summary row disappears. Below is an example with the iris dataset.

```
library(gt)
library(dplyr)

df <- iris |> select(Species, Sepal.Length)

gt(df) |> 
  grand_summary_rows(
    columns = Sepal.Length,
    fns = list(id = "mean", label = "Average") ~mean(., na.rm = TRUE),
    fmt = ~fmt_number(., use_seps = TRUE),
    side = "bottom"
  )

gt(df) |> 
  grand_summary_rows(
    columns = Sepal.Length,
    fns = list(id = "mean", label = "Average") ~mean(., na.rm = TRUE),
    fmt = ~fmt_number(., use_seps = TRUE),
    side = "bottom"
  ) |> 
  opt_interactive()
```

**Comment by olivroy** [comment] 2024-08-23 18:05
Thanks for the report! Duplicate of #1359

**Closed by olivroy** 2024-08-23 18:05 UTC
Labels: Type: ☹︎ Bug
